baseURL = 'https://windle.me.uk/'
languageCode = 'en-gb'
title = 'Sam Windle'
theme = 'hugo-marmot-swindle'


[blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/:month/:year/:title/"

[params]
  name = "Sam Windle"
  description = "Postgraduate Researcher | Uni of Notts | AMR | Bioinformatics"
  footer = """\
    &copy; [Sam Windle](https://windle.me.uk) 2024--{Year}\
    """
  social_header = "Follow me:"
  [[params.social]]
    name = "github"
    url = "https://github.com/Swindle98"

  [[params.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/sam-windle-a4b6bb1b9/"

  [[params.social]]
    name = "threads"
    url = "https://www.threads.net/@samswindle1"

  [[params.social]]
    name =  'orcID'
    url = 'https://orcid.org/0000-0003-4270-4498'

  #[[params.social]]
  #  name = "Scholar"
  #  url = ""

[menus]
  [[menu.main]]
    name = "Me"
    url = "/"
    weight = 1

 [[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 2

  [[menu.bottom]]
    name = "CV"
    url = "cv/"
    weight = 1

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

